export const products = [
    {
      "id": 1,
      "title": "ProTaper Gold Rotary Files Assorted",
      "slug": "protaper-gold-rotary-files-assorted",
      "category": "Endodontics",
      "description": "High-quality rotary files designed for efficient and safe root canal shaping. Offers flexibility and predictable performance.",
      "image": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRFyxv6BG3QGAXAw45NciMcYdkC5gEPgYx4CQ&s",
      "price": 5500,
      "discountedPrice": 4999,
      "discount": 9,
      "brand": "Dentsply",
      "stock": 45,
      "rating": 4.8,
      "reviewsCount": 127,
      "tags": ["Rotary Files", "Root Canal", "ProTaper"],
      "sku": "PTG-ASSORTED-21MM",
      "isFeatured": true,
      "createdAt": "2025-09-07T12:00:00Z",
      "updatedAt": "2025-09-07T12:00:00Z"
    },
    {
      "id": 2,
      "title": "Gutta Percha Points Size F2 (100pcs)",
      "slug": "gutta-percha-points-size-f2-100pcs",
      "category": "Endodontics",
      "description": "Premium gutta percha points for root canal obturation, ensuring tight and reliable sealing.",
      "image": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRfkCADnHp70Vk1MQMT1Uso5VVsUQZhJ4ngBw&s",
      "price": 1500,
      "discountedPrice": 1200,
      "discount": 20,
      "brand": "Meta Biomed",
      "stock": 200,
      "rating": 4.6,
      "reviewsCount": 98,
      "tags": ["Gutta Percha", "Obturation", "Root Canal"],
      "sku": "GP-F2-100",
      "isFeatured": false,
      "createdAt": "2025-09-07T12:05:00Z",
      "updatedAt": "2025-09-07T12:05:00Z"
    },
    {
      "id": 3,
      "title": "Apex Locator Mini (3rd Gen)",
      "slug": "apex-locator-mini-3rd-gen",
      "category": "Endodontics",
      "description": "Accurate and compact apex locator for determining working length during root canal therapy.",
      "image": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT1MUh3cpVUmYeEg3Xyojs2Hr4Qo1Dy_S7X8A&s",
      "price": 28000,
      "discountedPrice": 25999,
      "discount": 7,
      "brand": "Woodpecker",
      "stock": 15,
      "rating": 4.7,
      "reviewsCount": 54,
      "tags": ["Apex Locator", "Root Canal", "Endo Equipment"],
      "sku": "APX-LOC-3G",
      "isFeatured": true,
      "createdAt": "2025-09-07T12:10:00Z",
      "updatedAt": "2025-09-07T12:10:00Z"
    },
    {
      "id": 4,
      "title": "Endodontic K-Files 21mm (Stainless Steel)",
      "slug": "endodontic-k-files-21mm-stainless-steel",
      "category": "Endodontics",
      "description": "Durable stainless steel K-files for effective canal preparation and shaping.",
      "image": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRQpNCzpmBqsaLHtqin4tWydX5YDAlydeJPFA&s",
      "price": 1200,
      "discountedPrice": 1000,
      "discount": 17,
      "brand": "Mani",
      "stock": 300,
      "rating": 4.5,
      "reviewsCount": 143,
      "tags": ["K-Files", "Hand Files", "Canal Shaping"],
      "sku": "KF-21MM-SS",
      "isFeatured": false,
      "createdAt": "2025-09-07T12:15:00Z",
      "updatedAt": "2025-09-07T12:15:00Z"
    },
    {
      "id": 5,
      "title": "MTA Cement Root Repair Material",
      "slug": "mta-cement-root-repair-material",
      "category": "Endodontics",
      "description": "Mineral trioxide aggregate for root-end filling and perforation repair.",
      "image": "https://cdn11.bigcommerce.com/s-l4n17q06b5/images/stencil/1280x1280/products/10682/10379/MTA10__42279__69966.1693925630.jpg?c=1",
      "price": 8500,
      "discountedPrice": 7999,
      "discount": 6,
      "brand": "Angelus",
      "stock": 50,
      "rating": 4.9,
      "reviewsCount": 72,
      "tags": ["MTA", "Root Repair", "Endo Material"],
      "sku": "MTA-RRM-ANG",
      "isFeatured": true,
      "createdAt": "2025-09-07T12:20:00Z",
      "updatedAt": "2025-09-07T12:20:00Z"
    },
    {
      "id": 6,
      "title": "Endo Z Bur (Pack of 6)",
      "slug": "endo-z-bur-pack-of-6",
      "category": "Endodontics",
      "description": "High precision burs for safe and effective endodontic access opening.",
      "image": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ77LARVeZjYA_q7FTk8gCKcIwBd68StqgDBw&s",
      "price": 2500,
      "discountedPrice": 2200,
      "discount": 12,
      "brand": "SS White",
      "stock": 120,
      "rating": 4.4,
      "reviewsCount": 64,
      "tags": ["Endo Z", "Burs", "Access Cavity"],
      "sku": "EZB-6PK",
      "isFeatured": false,
      "createdAt": "2025-09-07T12:25:00Z",
      "updatedAt": "2025-09-07T12:25:00Z"
    },
    {
      "id": 7,
      "title": "Irrigation Needles Side-Vented (50pcs)",
      "slug": "irrigation-needles-side-vented-50pcs",
      "category": "Endodontics",
      "description": "Sterile side-vented irrigation needles for safe canal irrigation.",
      "image": "https://ae01.alicdn.com/kf/S5411869f791c4124872a09c4cf069a80r.jpg",
      "price": 900,
      "discountedPrice": 750,
      "discount": 17,
      "brand": "DiaDent",
      "stock": 500,
      "rating": 4.6,
      "reviewsCount": 89,
      "tags": ["Irrigation", "Needles", "Canal Disinfection"],
      "sku": "IRR-NEED-50",
      "isFeatured": false,
      "createdAt": "2025-09-07T12:30:00Z",
      "updatedAt": "2025-09-07T12:30:00Z"
    },
    {
      "id": 8,
      "title": "Calcium Hydroxide Paste Syringe",
      "slug": "calcium-hydroxide-paste-syringe",
      "category": "Endodontics",
      "description": "Ready-to-use calcium hydroxide paste for intracanal dressing.",
      "image": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS8vrnu69loG6vLlPcjsEQKkTVO21cDpMCeWQ&s",
      "price": 2200,
      "discountedPrice": 1999,
      "discount": 9,
      "brand": "Voco",
      "stock": 80,
      "rating": 4.7,
      "reviewsCount": 56,
      "tags": ["Calcium Hydroxide", "Intracanal", "Medication"],
      "sku": "CHP-SYR-VOCO",
      "isFeatured": false,
      "createdAt": "2025-09-07T12:35:00Z",
      "updatedAt": "2025-09-07T12:35:00Z"
    },
    {
      "id": 9,
      "title": "Paper Points Absorbent (200pcs)",
      "slug": "paper-points-absorbent-200pcs",
      "category": "Endodontics",
      "description": "Highly absorbent paper points for drying root canals effectively.",
      "image": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQYFog5cQdQEQlxdc8FRgvXCmBNc6XkJXxOSg&s",
      "price": 1100,
      "discountedPrice": 950,
      "discount": 14,
      "brand": "DiaDent",
      "stock": 250,
      "rating": 4.5,
      "reviewsCount": 110,
      "tags": ["Paper Points", "Drying", "Root Canal"],
      "sku": "PP-200-DD",
      "isFeatured": false,
      "createdAt": "2025-09-07T12:40:00Z",
      "updatedAt": "2025-09-07T12:40:00Z"
    },
    {
      "id": 10,
      "title": "Endo Motor with Apex Locator",
      "slug": "endo-motor-with-apex-locator",
      "category": "Endodontics",
      "description": "Advanced cordless endo motor with integrated apex locator for precision canal preparation.",
      "image": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTZ37S7iE8ep7abs0Kr4wnZMp447650M4-h9w&s",
      "price": 55000,
      "discountedPrice": 49999,
      "discount": 9,
      "brand": "Eighteeth",
      "stock": 10,
      "rating": 4.9,
      "reviewsCount": 35,
      "tags": ["Endo Motor", "Apex Locator", "Root Canal Equipment"],
      "sku": "EMAL-ET-01",
      "isFeatured": true,
      "createdAt": "2025-09-07T12:45:00Z",
      "updatedAt": "2025-09-07T12:45:00Z"
    },
    {
        "id": 11,
        "title": "Nitrile Examination Gloves (Latex-Free, 100pcs)",
        "slug": "nitrile-examination-gloves-latex-free-100pcs",
        "category": "Disposables",
        "description": "High-quality, powder-free nitrile gloves offering excellent protection and tactile sensitivity.",
        "image": "https://ik.imagekit.io/cpnw7c0xpe/Disposables/nitrile-gloves.png",
        "price": 1200,
        "discountedPrice": 999,
        "discount": 17,
        "brand": "SafeHands",
        "stock": 500,
        "rating": 4.9,
        "reviewsCount": 210,
        "tags": ["Latex-Free", "Exam Gloves", "Infection Control"],
        "sku": "NH-GLOVES-100",
        "isFeatured": true,
        "createdAt": "2025-09-07T13:00:00Z",
        "updatedAt": "2025-09-07T13:00:00Z"
      },
      {
        "id": 12,
        "title": "3-Ply Surgical Face Masks (50pcs Box)",
        "slug": "3-ply-surgical-face-masks-50pcs-box",
        "category": "Disposables",
        "description": "Disposable 3-ply surgical masks providing effective barrier protection in clinical settings.",
        "image": "https://ik.imagekit.io/cpnw7c0xpe/Disposables/surgical-masks.png",
        "price": 800,
        "discountedPrice": 699,
        "discount": 13,
        "brand": "ClearBreath",
        "stock": 1000,
        "rating": 4.7,
        "reviewsCount": 180,
        "tags": ["Face Masks", "Procedures", "Infection Control"],
        "sku": "CB-MASK50",
        "isFeatured": false,
        "createdAt": "2025-09-07T13:05:00Z",
        "updatedAt": "2025-09-07T13:05:00Z"
      },
      {
        "id": 13,
        "title": "Disposable Dental Bibs 2-Ply (200pcs)",
        "slug": "disposable-dental-bibs-2-ply-200pcs",
        "category": "Disposables",
        "description": "Absorbent 2-ply dental bibs with waterproof backing to protect patients during procedures.",
        "image": "https://ik.imagekit.io/cpnw7c0xpe/Disposables/dental-bibs.png",
        "price": 950,
        "discountedPrice": 799,
        "discount": 16,
        "brand": "SafeShield",
        "stock": 600,
        "rating": 4.8,
        "reviewsCount": 150,
        "tags": ["Bibs", "Patient Protection", "Procedure Essentials"],
        "sku": "SS-BIB200",
        "isFeatured": false,
        "createdAt": "2025-09-07T13:10:00Z",
        "updatedAt": "2025-09-07T13:10:00Z"
      },
      {
        "id": 14,
        "title": "Contour Tray Covers (100pcs)",
        "slug": "contour-tray-covers-100pcs",
        "category": "Disposables",
        "description": "Easy-to-fit tray covers that help maintain sterile work surfaces.",
        "image": "https://ik.imagekit.io/cpnw7c0xpe/Disposables/tray-covers.png",
        "price": 600,
        "discountedPrice": 499,
        "discount": 17,
        "brand": "ClinicWrap",
        "stock": 750,
        "rating": 4.6,
        "reviewsCount": 90,
        "tags": ["Tray Covers", "Sterility", "Procedure Essentials"],
        "sku": "CW-TRAY100",
        "isFeatured": false,
        "createdAt": "2025-09-07T13:15:00Z",
        "updatedAt": "2025-09-07T13:15:00Z"
      },
      {
        "id": 15,
        "title": "Cotton-Tipped Applicators (6\", 1000pcs)",
        "slug": "cotton-tipped-applicators-6in-1000pcs",
        "category": "Disposables",
        "description": "Versatile applicators for applying medicaments, ideal for endodontic procedures.",
        "image": "https://ik.imagekit.io/cpnw7c0xpe/Disposables/cotton-applicators.png",
        "price": 700,
        "discountedPrice": 599,
        "discount": 14,
        "brand": "TipClean",
        "stock": 800,
        "rating": 4.5,
        "reviewsCount": 120,
        "tags": ["Applicators", "Endodontic Use", "Precision"],
        "sku": "TC-APPL1000",
        "isFeatured": false,
        "createdAt": "2025-09-07T13:20:00Z",
        "updatedAt": "2025-09-07T13:20:00Z"
      },
      {
        "id": 16,
        "title": "Saliva Ejectors (100pcs)",
        "slug": "saliva-ejectors-100pcs",
        "category": "Disposables",
        "description": "Flexible, single-use saliva ejectors to maintain a dry work area during treatment.",
        "image": "https://ik.imagekit.io/cpnw7c0xpe/Disposables/saliva-ejectors.png",
        "price": 540,
        "discountedPrice": 499,
        "discount": 8,
        "brand": "SuctionEase",
        "stock": 900,
        "rating": 4.6,
        "reviewsCount": 110,
        "tags": ["Ejectors", "Moisture Control", "Disposable"],
        "sku": "SE-EJECT100",
        "isFeatured": false,
        "createdAt": "2025-09-07T13:25:00Z",
        "updatedAt": "2025-09-07T13:25:00Z"
      },
      {
        "id": 17,
        "title": "Air/Water Syringe Tips (Plastic, 500pcs)",
        "slug": "air-water-syringe-tips-plastic-500pcs",
        "category": "Disposables",
        "description": "Universal plastic tips compatible with most syringe handpieces.",
        "image": "https://ik.imagekit.io/cpnw7c0xpe/Disposables/syringe-tips.png",
        "price": 1600,
        "discountedPrice": 1399,
        "discount": 12,
        "brand": "AirFlow",
        "stock": 400,
        "rating": 4.7,
        "reviewsCount": 130,
        "tags": ["Syringe Tips", "Universal", "Endodontic Use"],
        "sku": "AF-SYR500",
        "isFeatured": false,
        "createdAt": "2025-09-07T13:30:00Z",
        "updatedAt": "2025-09-07T13:30:00Z"
      },
      {
        "id": 18,
        "title": "Disposable Prophy Angles (100pcs)",
        "slug": "disposable-prophy-angles-100pcs",
        "category": "Disposables",
        "description": "Pre-angled, single-use prophy angles for polishing and cleaning procedures.",
        "image": "https://ik.imagekit.io/cpnw7c0xpe/Disposables/prophy-angles.png",
        "price": 2200,
        "discountedPrice": 1999,
        "discount": 9,
        "brand": "ProClean",
        "stock": 350,
        "rating": 4.8,
        "reviewsCount": 150,
        "tags": ["Prophy Angles", "Cleaning", "Disposable"],
        "sku": "PC-ANGLE100",
        "isFeatured": true,
        "createdAt": "2025-09-07T13:35:00Z",
        "updatedAt": "2025-09-07T13:35:00Z"
      },
      {
        "id": 19,
        "title": "Sterilization Pouches (200pcs)",
        "slug": "sterilization-pouches-200pcs",
        "category": "Disposables",
        "description": "Steam-permeable pouches for instrument sterilization and storage.",
        "image": "https://ik.imagekit.io/cpnw7c0xpe/Disposables/steri-pouches.png",
        "price": 3200,
        "discountedPrice": 2999,
        "discount": 6,
        "brand": "SterileSeal",
        "stock": 450,
        "rating": 4.9,
        "reviewsCount": 80,
        "tags": ["Sterilization", "Pouches", "Infection Control"],
        "sku": "SS-POUCH200",
        "isFeatured": false,
        "createdAt": "2025-09-07T13:40:00Z",
        "updatedAt": "2025-09-07T13:40:00Z"
      },
      {
        "id": 20,
        "title": "Oral Care Swabs (Toothette, 100pcs)",
        "slug": "oral-care-swabs-toothette-100pcs",
        "category": "Disposables",
        "description": "Soft sponge-tip swabs for gentle oral care and moisture application.",
        "image": "https://ik.imagekit.io/cpnw7c0xpe/Disposables/oral-swabs.png",
        "price": 800,
        "discountedPrice": 699,
        "discount": 13,
        "brand": "OralFresh",
        "stock": 300,
        "rating": 4.5,
        "reviewsCount": 60,
        "tags": ["Swabs", "Oral Care", "Single Use"],
        "sku": "OF-SWAB100",
        "isFeatured": false,
        "createdAt": "2025-09-07T13:45:00Z",
        "updatedAt": "2025-09-07T13:45:00Z"
      }
  ]
  
  